version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  redis:
    container_name: redis
    image: redis:latest
    restart: always

  nginx:
    container_name: webserver
    depends_on:
      - php
    build:
      context: .
      dockerfile: ./docker/containers/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./site:/var/www/html
      - ./docker/containers/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    image: php:8.1-fpm-alpine
    volumes:
      - ./site:/var/www/html

volumes:
  db_data: {}
